// ignore_for_file: unused_import

import 'package:flutter/material.dart';
const List<String> cardIcons = <String>[
  'assets/images/apps.png',
  'assets/images/java.png',
  'assets/images/html.png',
  'assets/images/python.png',
  'assets/images/js.png',
  'assets/images/programming-language.png',
  'assets/images/google.png',
  'assets/images/logo.png',
  'assets/images/profile.png',
  'assets/images/library.png',
  'assets/images/css-3.png',
  'assets/images/github.png',
  'assets/images/database-storage.png',
  'assets/images/django.png',
  'assets/images/c-.png',
  'assets/images/c-sharp.png',
  'assets/images/bootstrap.png',
  'assets/images/xml.png',
  'assets/images/security.png',
  'assets/images/nodejs.png',
  'assets/images/asp.png',
  'assets/images/facebook.png',
  'assets/images/google.png',
  'assets/images/quiz.png',
  'assets/images/gamepad.png',
  'assets/images/trophy.png',
  'assets/images/photoshop.png',
  'assets/images/headset.png',
  'assets/images/vk.png',
  'assets/images/world.png',
  'assets/images/gift.png',
  'assets/images/coins.png',
  'assets/images/piggy-bank.png',
  'assets/images/refresh.png',
  'assets/images/lock.png',
  'assets/images/info.png',
  'assets/images/trash.png',
  'assets/images/heart.png',
  'assets/images/acrobat.png',
  'assets/images/apple.png',
  'assets/images/android.png',
  'assets/images/app-store-ios.png',
];
